### ISSUE TITLE
JavaScript Capstone project code review request

### ISSUE THREAD

**Issue by inspecta** [Khaled-AlKhateeb/YouFlex#21]
**Link to the project**
https://github.com/Khaled-AlKhateeb/Kanban-Board/

**NOTE:**
We are two people working on this project
Student A - @inspecta 
Student B - @Khaled-AlKhateeb

**Comment by ha-manel** [comment]
# Hey Team 👋 
Your project is complete, the kanban board is set correctly
You can now start working 👍 
Good luck 😊

**Comment by inspecta** [comment]
Thank you @ha-manel
